fix(backend): add quote to deploy script

diff --git a/.github/workflows/back-s3-ci.yml b/.github/workflows/back-s3-ci.yml
--- a/.github/workflows/back-s3-ci.yml
+++ b/.github/workflows/back-s3-ci.yml
@@ -30,7 +30,12 @@ jobs:
           aws-region: ${{ env.DEFAULT_BUCKET_REGION }}
 
       - name: Zip backend files
-        run: zip -r $DEPLOY_FILENAME ./backend
+        run: zip -r "$DEPLOY_FILENAME" ./backend
 
       - name: Deploy code to AWS S3
-        run: aws s3 cp ./$DEPLOY_FILENAME s3://$S3_BUCKET --region $DEFAULT_BUCKET_REGION
+        run: |
+          aws s3 cp "./$DEPLOY_FILENAME" "s3://$S3_BUCKET/" --region "$DEFAULT_BUCKET_REGION"
+          if [ $? -ne 0 ]; then
+            echo "Failed to upload file to S3"
+            exit 1
+          fi
